# GitHub Actions workflow for running unit tests on the GithubBackup script

name: Python Test Suite

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Check out repository
      uses: actions/checkout@v4

    # Step 2: Set up Python environment
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    # Step 3: Install any dependencies (add requirements.txt if needed.
    - name: Install test dependencies
      run: |
        python -m pip install --upgrade pip
      # Tolerates absence of requirements.txt
        pip install -r requirements.txt || true
        pip install pytest

    # Step 4: Run tests
    - name: Run unit tests with unittest
      run: |
        python -m unittest discover -s tests